# Configuration file for custom user settings

if(RENESAS_IDE AND RENESAS_IDE STREQUAL "e2studio")
    set(RASC_EXE_PATH "echo")
    message(NOTICE "RENESAS_IDE is defined, so RASC_EXE_PATH set to echo for information purposes")
elseif(DEFINED RASC_EXE_PATH)
    message("Using RASC_EXE_PATH defined via CLI -D: ${RASC_EXE_PATH}")
elseif(DEFINED ENV{RASC_EXE_PATH})
    set(RASC_EXE_PATH $ENV{RASC_EXE_PATH})
    message("Using RASC_EXE_PATH defined in environment: ${RASC_EXE_PATH}")
else ()
    set(RASC_EXE_PATH "echo")
    message("Using RASC_EXE_PATH generated by FSP application: ${RASC_EXE_PATH}")
endif()
