#ifndef APP_BOARD_CONFIG_H_
#define APP_BOARD_CONFIG_H_

#include "bsp_api.h"

// Board pin and instance configuration. Keep board-specific hardware choices here,
// not in CMake presets.

#define APP_IR_RX_PIN BSP_IO_PORT_00_PIN_05
#define APP_IR_TX_PIN BSP_IO_PORT_01_PIN_15

#define IRREMOTE_RA4M2_DEMO_RX_PIN APP_IR_RX_PIN
#define IRREMOTE_RA4M2_DEMO_TX_PIN APP_IR_TX_PIN

#define APP_OLED_DC_PIN BSP_IO_PORT_01_PIN_13
#define APP_OLED_RESET_PIN BSP_IO_PORT_01_PIN_14
#define APP_OLED_SPI_INSTANCE g_oled_spi
#define APP_OLED_WIDTH 128
#define APP_OLED_HEIGHT 64

#define APP_KEY_SELECT_PIN BSP_IO_PORT_04_PIN_00
#define APP_KEY_CONFIRM_PIN BSP_IO_PORT_04_PIN_01
#define APP_KEY_BACK_PIN BSP_IO_PORT_04_PIN_02
#define APP_KEY_ACTIVE_LEVEL BSP_IO_LEVEL_LOW

#define APP_IR_RECV_BUFFER_SIZE 1024
#define APP_IR_RECV_TIMEOUT_MS 50

#define APP_TRANSPORT_UART_BAUD 115200
#define APP_TRANSPORT_TCP_PORT 8765
#define APP_BLE_GATT_SERVICE_INDEX 1
#define APP_BLE_GATT_WRITE_CHAR_INDEX 5
#define APP_BLE_GATT_NOTIFY_CHAR_INDEX 6
#define APP_BLE_NOTIFY_CHUNK_SIZE 20

#endif
