#include "hal_data.h"
#include "Arduino.h"
#include "IRrecv.h"
#include "IRsend.h"

#ifndef IRREMOTE_RA4M2_SEND_DEMO
#define IRREMOTE_RA4M2_SEND_DEMO 0
#endif

#ifndef IRREMOTE_RA4M2_RECV_DEMO
#define IRREMOTE_RA4M2_RECV_DEMO 0
#endif

#ifndef IRREMOTE_RA4M2_DEMO_TX_PIN
#define IRREMOTE_RA4M2_DEMO_TX_PIN BSP_IO_PORT_00_PIN_05
#endif

#ifndef IRREMOTE_RA4M2_DEMO_RX_PIN
#define IRREMOTE_RA4M2_DEMO_RX_PIN BSP_IO_PORT_00_PIN_05
#endif

#ifndef IRREMOTE_RA4M2_RECV_BUFFER_SIZE
#define IRREMOTE_RA4M2_RECV_BUFFER_SIZE 1024
#endif

#ifndef IRREMOTE_RA4M2_RECV_TIMEOUT_MS
#define IRREMOTE_RA4M2_RECV_TIMEOUT_MS 50
#endif

#ifndef IRREMOTE_RA4M2_DEBUG_RAW_DUMP_SIZE
#define IRREMOTE_RA4M2_DEBUG_RAW_DUMP_SIZE 256
#endif

volatile decode_type_t g_irremote_last_decode_type = UNKNOWN;
volatile uint64_t g_irremote_last_value = 0;
volatile uint16_t g_irremote_last_bits = 0;
volatile uint16_t g_irremote_last_rawlen = 0;
volatile bool g_irremote_last_overflow = false;
volatile uint32_t g_irremote_decode_count = 0;
volatile uint16_t g_irremote_last_raw_dump_len = 0;
volatile uint16_t g_irremote_last_rawbuf[IRREMOTE_RA4M2_DEBUG_RAW_DUMP_SIZE] = {};

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif

#if IRREMOTE_RA4M2_SEND_DEMO
    IRsend irsend(IRREMOTE_RA4M2_DEMO_TX_PIN);
    irsend.begin();

    while (true)
    {
        irsend.sendNEC(irsend.encodeNEC(0x00FF, 0x10));
        delay(1000);
    }
#elif IRREMOTE_RA4M2_RECV_DEMO
    IRrecv irrecv(IRREMOTE_RA4M2_DEMO_RX_PIN,
                  IRREMOTE_RA4M2_RECV_BUFFER_SIZE,
                  IRREMOTE_RA4M2_RECV_TIMEOUT_MS);
    decode_results results;
    irrecv.enableIRIn(true);

    while (true)
    {
        if (irrecv.decode(&results))
        {
            g_irremote_last_decode_type = results.decode_type;
            g_irremote_last_value = results.value;
            g_irremote_last_bits = results.bits;
            g_irremote_last_rawlen = results.rawlen;
            g_irremote_last_overflow = results.overflow;
            g_irremote_last_raw_dump_len =
                (results.rawlen < IRREMOTE_RA4M2_DEBUG_RAW_DUMP_SIZE) ?
                results.rawlen : IRREMOTE_RA4M2_DEBUG_RAW_DUMP_SIZE;

            for (uint16_t i = 0; i < g_irremote_last_raw_dump_len; i++)
            {
                g_irremote_last_rawbuf[i] = results.rawbuf[i];
            }

            g_irremote_decode_count++;
            irrecv.resume();
        }
    }
#else
    while (true)
    {
        __WFI();
    }
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
